stages:
  - build
  - test

build:
  stage: build
  tags:
    - macos
  before_script:
    - ./post-setup.sh
  script:
    - swiftc main.swift -framework Metal -o vector_add
    - chmod +x vector_add
  artifacts:
    paths:
      - vector_add

test:
  stage: test
  tags:
    - macos
  before_script:
    - ./post-setup.sh
  script:
    - ./vector_add
  dependencies:
    - build